org: moulout
app: serverless
service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  sendResponse:
    handler: api/index.sendResponse
    events:
      -httpApi:
        path: /api/results
        method: post
        request: 
          schemas:
            application/json: ${file(./schemas/sendResponse.json)}
  getResult:
    hander: api/index.getResult
    events:
     -httpApi:
        path: /api/result/{id}
        method: get
